# Generated by Django 5.0.6 on 2024-10-17 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_petmodel_aded_by_petmodel_age'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petmodel',
            name='aded_by',
        ),
        migrations.AddField(
            model_name='petmodel',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='image',
            field=models.ImageField(upload_to='pet/images/'),
        ),
    ]
