# Generated by Django 5.0.6 on 2024-10-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmodel',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
